
post http://localhost:5000/users/register
Content-Type: application/json

{
    "username":"islamhanafi",
    "firstName":"islam",
    "lastName":"hanafi",
    "email":"islam@islam.com",
    "password":"1234"
}

###

get http://localhost:5000/users/mybooks

###

post http://localhost:5000/users/login
Content-Type: application/json

{
    "email":"islam@islam.com",
    "password":"1234"
}

###
GET http://localhost:5000/category HTTP/1.1
###
POST http://localhost:5000/category/new HTTP/1.1
Content-Type: application/json

{
    "name":"art"
}

###
GET http://localhost:5000/author HTTP/1.1

###

GET http://localhost:5000/author/123 HTTP/1.1

###
POST  http://localhost:5000/author HTTP/1.1
Content-Type: application/json

{
    "firstName":"ddddd",
    "lastName":"ddddd",
    "dateOfBirth":"2002-12-09"
}
###
DELETE   http://localhost:5000/author/5ebe1705e4e7e831e2cf47cb HTTP/1.1

###
PUT   http://localhost:5000/author/5ebe17c23ee2e0347407e6f0 HTTP/1.1
Content-Type: application/json

{
    "firstName":"a",
    "lastName":"b",
    "dateOfBirth":"2002-12-09"
}

###
POST http://localhost:5000/books/new HTTP/1.1
Content-Type: application/json

{
    "name":"book1",
    "image":"photo.jpg",
    "averageRating":3,
    "author": "5ec7d4a1b84a34568431cb7c",
    "category": "5ec7ab2f70d9442321454811"
}

###
GET http://localhost:5000/books HTTP/1.1

###